name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-image-nest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD_CI }}

      - name: Build image
        run: |
          docker build . --tag ghcr.io/leifermendez/nestjs-curso:latest
          docker push ghcr.io/leifermendez/nestjs-curso:latest